#!/bin/bash
diff openjpeg/openjpeg-lib/bio.c ~/dwtlift-pi/pi-myTTEncoder/src/bio.c
diff openjpeg/openjpeg-lib/bio.h ~/dwtlift-pi/pi-myTTEncoder/src/bio.h
diff openjpeg/openjpeg-lib/cio.c ~/dwtlift-pi/pi-myTTEncoder/src/cio.c
diff openjpeg/openjpeg-lib/cio.h ~/dwtlift-pi/pi-myTTEncoder/src/cio.h
diff openjpeg/openjpeg-lib/dwt.c ~/dwtlift-pi/pi-myTTEncoder/src/dwt.c
diff openjpeg/openjpeg-lib/dwt.h ~/dwtlift-pi/pi-myTTEncoder/src/dwt.h
diff openjpeg/openjpeg-lib/dwtlift.c ~/dwtlift-pi/pi-myTTEncoder/src/dwtlift.c
diff openjpeg/openjpeg-lib/dwtlift.h ~/dwtlift-pi/pi-myTTEncoder/src/dwtlift.h
diff openjpeg/openjpeg-lib/event.c ~/dwtlift-pi/pi-myTTEncoder/src/event.c
diff openjpeg/openjpeg-lib/event.h ~/dwtlift-pi/pi-myTTEncoder/src/event.h
diff openjpeg/openjpeg-lib/format_defs.h ~/dwtlift-pi/pi-myTTEncoder/src/format_defs.h
diff openjpeg/openjpeg-lib/function_list.h ~/dwtlift-pi/pi-myTTEncoder/src/function_list.h
diff openjpeg/openjpeg-lib/function_list.c ~/dwtlift-pi/pi-myTTEncoder/src/function_list.c 
diff openjpeg/openjpeg-lib/image.h ~/dwtlift-pi/pi-myTTEncoder/src/image.h
diff openjpeg/openjpeg-lib/image.c ~/dwtlift-pi/pi-myTTEncoder/src/image.c 
diff openjpeg/openjpeg-lib/invert.c ~/dwtlift-pi/pi-myTTEncoder/src/invert.c
diff openjpeg/openjpeg-lib/invert.h ~/dwtlift-pi/pi-myTTEncoder/src/invert.h
diff openjpeg/openjpeg-lib/j2k.c ~/dwtlift-pi/pi-myTTEncoder/src/j2k.c
diff openjpeg/openjpeg-lib/j2k.h ~/dwtlift-pi/pi-myTTEncoder/src/j2k.h
diff openjpeg/openjpeg-lib/jp2.c ~/dwtlift-pi/pi-myTTEncoder/src/jp2.c
diff openjpeg/openjpeg-lib/jp2.h ~/dwtlift-pi/pi-myTTEncoder/src/jp2.h
diff openjpeg/openjpeg-lib/mct.c ~/dwtlift-pi/pi-myTTEncoder/src/mct.c
diff openjpeg/openjpeg-lib/mct.h ~/dwtlift-pi/pi-myTTEncoder/src/mct.h
diff openjpeg/openjpeg-lib/mqc.c ~/dwtlift-pi/pi-myTTEncoder/src/mqc.c
diff openjpeg/openjpeg-lib/mqc.h ~/dwtlift-pi/pi-myTTEncoder/src/mqc.h
diff openjpeg/openjpeg-lib/mqc_inl.h ~/dwtlift-pi/pi-myTTEncoder/src/mqc_inl.h
diff openjpeg/openjpeg-lib/openjpeg.c ~/dwtlift-pi/pi-myTTEncoder/src/openjpeg.c
diff openjpeg/openjpeg-lib/openjpeg.h ~/dwtlift-pi/pi-myTTEncoder/src/openjpeg.h
diff openjpeg/openjpeg-lib/opj_clock.c ~/dwtlift-pi/pi-myTTEncoder/src/opj_clock.c
diff openjpeg/openjpeg-lib/opj_clock.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_clock.h
diff openjpeg/openjpeg-lib/opj_codec.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_codec.h
diff openjpeg/openjpeg-lib/opj_common.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_common.h
diff openjpeg/openjpeg-lib/opj_config.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_config.h
diff openjpeg/openjpeg-lib/opj_config_private.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_config_private.h
diff openjpeg/openjpeg-lib/opj_includes.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_includes.h
diff openjpeg/openjpeg-lib/opj_intmath.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_intmath.h
diff openjpeg/openjpeg-lib/opj_inttypes.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_inttypes.h
diff openjpeg/openjpeg-lib/opj_malloc.c ~/dwtlift-pi/pi-myTTEncoder/src/opj_malloc.c
diff openjpeg/openjpeg-lib/pi.h ~/dwtlift-pi/pi-myTTEncoder/src/pi.h 
diff openjpeg/openjpeg-lib/opj_stdint.h ~/dwtlift-pi/pi-myTTEncoder/src/opj_stdint.h
diff openjpeg/openjpeg-lib/pi.c ~/dwtlift-pi/pi-myTTEncoder/src/pi.c
diff openjpeg/openjpeg-lib/pi.h ~/dwtlift-pi/pi-myTTEncoder/src/pi.h
diff openjpeg/openjpeg-lib/sparse_array.h ~/dwtlift-pi/pi-myTTEncoder/src/sparse_array.h
diff openjpeg/openjpeg-lib/sparse_array.c ~/dwtlift-pi/pi-myTTEncoder/src/sparse_array.c
diff openjpeg/openjpeg-lib/t1.h ~/dwtlift-pi/pi-myTTEncoder/src/t1.h
diff openjpeg/openjpeg-lib/t1.c ~/dwtlift-pi/pi-myTTEncoder/src/t1.c
diff openjpeg/openjpeg-lib/t1_luts.h ~/dwtlift-pi/pi-myTTEncoder/src/t1_luts.h
diff openjpeg/openjpeg-lib/t2.h ~/dwtlift-pi/pi-myTTEncoder/src/t2.h
diff openjpeg/openjpeg-lib/t2.c ~/dwtlift-pi/pi-myTTEncoder/src/t2.c
diff openjpeg/openjpeg-lib/tcd.h ~/dwtlift-pi/pi-myTTEncoder/src/tcd.h
diff openjpeg/openjpeg-lib/tcd.c ~/dwtlift-pi/pi-myTTEncoder/src/tcd.c
diff openjpeg/openjpeg-lib/tgt.h ~/dwtlift-pi/pi-myTTEncoder/src/tgt.h
diff openjpeg/openjpeg-lib/tgt.c ~/dwtlift-pi/pi-myTTEncoder/src/tgt.c
diff openjpeg/openjpeg-lib/thread.h ~/dwtlift-pi/pi-myTTEncoder/src/thread.h
diff openjpeg/openjpeg-lib/thread.c ~/dwtlift-pi/pi-myTTEncoder/src/thread.c
diff openjpeg/openjpeg-lib/tls_keys.h ~/dwtlift-pi/pi-myTTEncoder/src/tls_keys.h
